// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { SectionConfig } from 'evolution-common/lib/services/questionnaire/types';

export const widgetsNames: SectionConfig['widgets'] = ['householdMembers', 'household_save'];

export const householdMembersWidgetsNames: SectionConfig['widgets'] = [
    'personNickname',
    'personAge',
    'personGender',
    'personWorkerType',
    'personStudentType',
    'personSchoolType',
    'personOccupation',
    'personDrivingLicenseOwner',
    'personCarSharingMember',
    // 'personTransitFares',
    'personHasDisability',
    'personWorkLocationType',
    'personSchoolLocationType',
    'personUsualWorkPlaceName',
    'personUsualWorkPlaceGeography',
    'personUsualSchoolPlaceName',
    'personUsualSchoolPlaceGeography'
    // 'personTravelToWorkDays',
    // 'personRemoteWorkDays',
    // 'personTravelToStudyDays',
    // 'personRemoteStudyDays'
];
