survey_folder_path: ../../../survey
excel_file_path: ../../../survey/references/OD_nationale_quebec_2025.xlsx

enabled_scripts:
    generate_excel: false
    generate_section_configs: false
    generate_sections: true
    generate_widgets_configs: true
    generate_widgets: true
    generate_conditionals: true
    generate_choices: true
    generate_input_range: true
    generate_labels: true
    generate_UI_tests: true
    generate_questionnaire_list: true
    generate_questionnaire_dictionary: true
