// This file was automatically generated by the Evolution Generator.
// The Evolution Generator is used to automate the creation of consistent, reliable code.
// Any changes made to this file will be overwritten.

import { TFunction } from 'i18next';
import _escape from 'lodash/escape';
import * as defaultInputBase from 'evolution-frontend/lib/components/inputs/defaultInputBase';
import { defaultConditional } from 'evolution-common/lib/services/widgets/conditionals/defaultConditional';
import * as WidgetConfig from 'evolution-common/lib/services/questionnaire/types';
import * as validations from 'evolution-common/lib/services/widgets/validations/validations';
import * as odSurveyHelpers from 'evolution-common/lib/services/odSurvey/helpers';
import * as choices from '../../common/choices';
import * as conditionals from '../../common/conditionals';
import * as customConditionals from '../../common/customConditionals';
import * as customWidgets from './customWidgets';
import * as customChoices from './customChoices';

// activePersonTitle

// buttonSwitchPerson

// personVisitedPlacesTitle

// personVisitedPlacesMap

// personVisitedPlaces

// visitedPlaceActivityCategory

// visitedPlaceActivity

export const visitedPlaceOnTheRoadDepartureType = customWidgets.visitedPlaceOnTheRoadDepartureType;

export const visitedPlaceOnTheRoadArrivalType: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'onTheRoadArrivalType',
    twoColumns: false,
    containsHtml: false,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('visitedPlaces:onTheRoadArrivalType', {
            nickname,
            count: countPersons,
            context: activePerson?.gender || activePerson?.sexAssignedAtBirth
        });
    },
    choices: customChoices.onTheRoadArrivalTypeCustomChoices,
    conditional: customConditionals.currentPlaceWorkOnTheRoadAndNoNextPlaceCustomConditional,
    validations: validations.requiredValidation
};

export const visitedPlaceAlreadyVisited: WidgetConfig.InputRadioType = {
    ...defaultInputBase.inputRadioBase,
    path: 'alreadyVisitedBySelfOrAnotherHouseholdMember',
    twoColumns: false,
    containsHtml: true,
    label: (t: TFunction, interview, path) => {
        const activePerson = odSurveyHelpers.getPerson({ interview, path });
        const nickname = _escape(activePerson?.nickname || t('survey:noNickname'));
        const countPersons = odSurveyHelpers.countPersons({ interview });
        return t('visitedPlaces:alreadyVisitedBySelfOrAnotherHouseholdMember', {
            nickname,
            count: countPersons
        });
    },
    choices: choices.yesNo,
    conditional: customConditionals.alreadyVisitedPlaceCustomConditional,
    validations: validations.requiredValidation
};

// Custom because of the choices
export const visitedPlaceShortcut = customWidgets.visitedPlaceShortcut;

// Custom until Evolution supports shortcuts
export const visitedPlaceName = customWidgets.visitedPlaceName;

// Custom until Evolution supports shortcuts
export const visitedPlaceGeography = customWidgets.visitedPlaceGeography;

// Custom because of the complexity of the widget, implying moving activities
export const visitedPlacePreviousPreviousDepartureTime = customWidgets.visitedPlacePreviousPreviousDepartureTime;

// Custom because of the complexity of the widget, implying moving activities
export const visitedPlacePreviousArrivalTime = customWidgets.visitedPlacePreviousArrivalTime;

// Custom because of the complexity of the widget, implying moving activities
export const visitedPlacePreviousDepartureTime = customWidgets.visitedPlacePreviousDepartureTime;

// Custom because it’s a time widget, not supported by generator
export const visitedPlaceArrivalTime = customWidgets.visitedPlaceArrivalTime;

// visitedPlaceNextPlaceCategory

// Custom because it’s a time widget, not supported by generator
export const visitedPlaceDepartureTime = customWidgets.visitedPlaceDepartureTime;

// Custom because they are action button, but not to go to next section
export const buttonSaveVisitedPlace = customWidgets.buttonSaveVisitedPlace;

// Custom because they are action button, but not to go to next section
export const buttonCancelVisitedPlace = customWidgets.buttonCancelVisitedPlace;

// Custom because they are action button, but not to go to next section
export const buttonDeleteVisitedPlace = customWidgets.buttonDeleteVisitedPlace;

// buttonVisitedPlacesConfirmNextSection
